# Generated by Django 4.0.4 on 2022-06-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='estado',
            field=models.CharField(max_length=30),
        ),
    ]
