# Generated by Django 4.0.4 on 2022-06-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivo', '0002_alter_archivo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
