# Generated by Django 4.0.4 on 2022-06-07 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Integrante', '0002_integrante_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrante',
            name='autor',
        ),
    ]
